version: '2'
services:
  node1:
    # image: ethereum/client-go
    image: ethereum/client-go:alltools-v1.10.26
    container_name: node1
    command: 
      --networkid=21021
      --port=30300
      --maxpeers=10
      --allow-insecure-unlock
      --nodiscover
      --http
      --http.addr="0.0.0.0"
      --http.port=8545
      --http.corsdomain="*"
      --http.api="admin, debug, web3, eth, txpool, personal, ethash, miner, net"
      --unlock="c8f0cf0a3d337332ABecAd0102bE3bd5BB4Edc55"
      --password="/root/.ethereum/password"
      --miner.etherbase="c8f0cf0a3d337332ABecAd0102bE3bd5BB4Edc55" 
      --ethstats="node1:SURF@eth-netstats:3000"
      --gcmode="archive"
      --syncmode="full"
      --mine 
      --miner.gasprice=0
      # --miner.threads=1
    volumes:
      - ./data/data-node1:/root/.ethereum:rw
    ports:
      - "30300:30300" # peer 연결용
      - "30300:30300/udp" # peer 연결용
      - "8545:8545"   # remix 연결용
    networks:
      priv-eth-net:
        ipv4_address: 172.15.200.2

  node2:
    # image: ethereum/client-go
    image: ethereum/client-go:alltools-v1.10.26
    container_name: node2
    depends_on:
      - node1
    command: 
      --networkid=21021
      --port=30304
      --maxpeers=10
      --allow-insecure-unlock
      --nodiscover
      --http
      --http.addr="0.0.0.0"
      --http.port=8546
      --http.corsdomain="*"
      --http.api="admin, debug, web3, eth, txpool, personal, ethash, miner, net"
      --ethstats="node2:SURF@eth-netstats:3000"
    volumes:
      - ./data/data-node2:/root/.ethereum:rw
    ports:
      - "30304:30304" # peer 연결용
      - "30304:30304/udp" # peer 연결용
      - "8546:8546"   # remix 연결용
    networks:
      priv-eth-net:
        ipv4_address: 172.15.200.3

  eth-netstats:
    image: kamael/eth-netstats
    container_name: eth-netstats
    depends_on:
      - node1
    ports:
      - "3002:3000" # 네트워크 모니터링 
    environment:
      - WS_SECRET=SURF
    networks:
      priv-eth-net:
        ipv4_address: 172.15.200.4

  blockscout:
    hostname: blockscout
    depends_on:
      - node1
      - db
    # image: blockscout
    build:
      context: ./blockscout
      args:
        COIN: ABC
    restart: on-failure
    env_file:
      - ./blockscout/common-blockscout.env
    environment:
      ETHEREUM_JSONRPC_VARIANT: geth
      BLOCK_TRANSFORMER: clique
      ETHEREUM_JSONRPC_HTTP_URL: http://172.15.200.2:8545/
      ETHEREUM_JSONRPC_WS_URL: ws://172.15.200.2:8546
      # DATABASE_URL: postgresql://postgres:gkgk^^@db:5432/blockscout?ssl=false
      DATABASE_URL: postgresql://postgres:gkgk^^@172.21.0.2:5432/blockscout?ssl=false
      ECTO_USE_SSL: "false"
      SUBNETWORK: "Dev"
      SECRET_KEY_BASE: VTIB3uHDNbvrY0+60ZWgUoUBKDn9ppLR8MI4CpRz4/qLyEFs54ktJfaNT6Z221No
      DISABLE_EXCHANGE_RATES: "true"
      INDEXER_DISABLE_BLOCK_REWARD_FETCHER: "true"
      LINK_TO_OTHER_EXPLORERS: "false"
      SUPPORTED_CHAINS: "[]"
      APPS_MENU: 0
      HIDE_FOOTER: 1
      SHOW_DASHBOARD_GRAPH: 0
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 1
      INDEXER_MEMORY_LIMIT: 2
      SHOW_ADDRESS_MARKETCAP_PERCENTAGE: 0
      DISABLE_READ_API: 0
      DISABLE_WRITE_API: 0
    ports:
      - 8082:4000
  db:
    image: postgres:13.6
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: 'gkgk^^'
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432
    
    volumes:
      - /home/dev/www/ABC/data/db-data:/var/lib/postgresql/data
networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.15.200.0/28